name: CI - Development 2

on:
  push:
    branches: [ main ]


jobs:

  security:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    

      - name: Instalar dependências
        run: npm install

      - name: Secret Scan
        uses: gitleaks/gitleaks-action@v2
  
      - name: Verificar vulnerabilidades
        run: npm audit --audit-level=high


  quality:

    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Run Coverage
        run: npm run coverage

      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=raffamir_pipeline-ci
            -Dsonar.organization=raffamir-1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build:

    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    

      - name: Instalar dependências
        run: npm install

      - name: Gerar artefato
        run: zip -r app.zip .

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app.zip

  test:

    needs: build
    strategy:
        matrix:
         node-version: [20, 22, 24]
         os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Extrair artefato
        run: unzip app.zip

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependências
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test