name: CI - Development 2

on:
  push:
    branches: [ main ]


jobs:

  security:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    

      - name: Instalar dependências
        run: npm install

      - name: Secret Scan
        uses: gitleaks/gitleaks-action@v2
  
      - name: Verificar vulnerabilidades
        run: npm audit --audit-level=high


  quality:

    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Run Coverage
        run: npm run coverage

      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=raffamir_pipeline-ci
            -Dsonar.organization=raffamir-1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build:

    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # O "Login" é necessário para enviar a imagem para o Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Aqui o Docker faz o npm install e configura o ambiente sozinho
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: raffamir/pipeline-ci:latest # Use o seu usuário do Docker Hub

  test:

    needs: build
    runs-on: ubuntu-latest # Não precisa mais de Windows/Mac, o Docker isola o SO
    
    steps:
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Em vez de unzip e setup-node, você apenas "chama" a imagem pronta
      - name: Rodar testes dentro do Container
        run: docker run raffamir/pipeline-ci:latest npm test