name: CI - Development 2

on:
  push:
    branches: [ main ]


jobs:

  security:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    

      - name: Instalar dependências
        run: npm install

      - name: Secret Scan
        uses: gitleaks/gitleaks-action@v2
  
      - name: Verificar vulnerabilidades
        run: npm audit --audit-level=high


  quality:

    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    

      - name: Instalar dependências
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Run Coverage
        run: npm run coverage

      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=raffamir_pipeline-ci
            -Dsonar.organization=raffamir-1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build:

    needs: quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build com Docker Compose
        run: docker compose build

      - name: Push com Docker Compose
        run: docker compose push

# --- STAGE 2: TEST (Não precisa de login se a imagem for pública) ---
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Subir Ambiente de Teste
        run: docker compose up -d

      - name: Validar Comunicação (Ping)
        run: docker compose exec -T calculadora-app ping -c 1 servico-vizinho

      - name: Rodar Testes Unitários (NPM)
        run: docker compose exec -T calculadora-app npm test